version: '3.9'
services:
  python:
    build:
      context: .
      target: local
    container_name: tmpl-django-rest-py
    tty: true
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000" #porta usada para debug
      - "8005:8000"
    command: python manage.py runserver 0.0.0.0:8000
