version: "3.4"
services:
  php:
    build:
      context: .
      target: local
    container_name: ${PROJECT_NAME:-tmpl-api-rest}-app
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
      - ./docker/php/nginx/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    environment:
      APP_ENV: dev
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG: "client_host=192.168.1.41"
  nginx:
    image: nginx:latest
    container_name: ${PROJECT_NAME:-tmpl-api-rest}-nginx
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./docker/php/nginx:/etc/nginx/conf.d/
    ports:
      - 8086:80
    depends_on:
      - php
