version: "3.9"
services:
  python:
    build:
      context: .
      target: local
    container_name: ${PROJECT_NAME}-py
    tty: true
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000" #porta usada para debug