version: '3.9'
services:
  php:
    build:
      context: .
      target: local
    container_name: tmpl-slim-php
    volumes:
      - ./:/var/www
      - ./docker-compose/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker-compose/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    environment:
      XDEBUG_CONFIG: "client_host=192.168.1.41"
  nginx:
    image: nginx:latest
    container_name: tmpl-slim-nginx
    restart: unless-stopped
    volumes:
      - ./:/var/www/
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    ports:
      - 8086:80
    depends_on:
      - php
