version: '3.9'
services:
  python:
    build:
      context: .
      target: local
    container_name: tmpl-fastapi-py
    tty: true
    volumes:
      - .:/usr/src/app
    ports:
      - "3001:3000"
      - "8006:8000"
    